import { Product } from './schemas/product.schema';

export const products: Partial<Product>[] = [
  {
    name: "iPhone 15 Pro",
    description: "Apple smartphone with A17 Pro chip and advanced camera system.",
    price: 999,
    stock: 20,
    category: "Smartphones",
    imageUrl: "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2015%20Pro/1.png",
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    description: "Premium Android smartphone with powerful performance.",
    price: 1199,
    stock: 15,
    category: "Smartphones",
    imageUrl: "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S24%20Ultra/1.png",
  },
  {
    name: "MacBook Pro",
    description: "Professional laptop with high performance and Retina display.",
    price: 1999,
    stock: 10,
    category: "Laptops",
    imageUrl: "https://cdn.dummyjson.com/products/images/laptops/MacBook%20Pro/1.png",
  },
  {
    name: "Wireless Headphones",
    description: "Noise cancelling headphones with premium sound quality.",
    price: 199,
    stock: 35,
    category: "Audio",
    imageUrl: "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods%20Max%20Silver/1.png",
  },
  {
    name: "Gaming Keyboard",
    description: "RGB mechanical keyboard designed for gamers.",
    price: 89,
    stock: 40,
    category: "Gaming",
    imageUrl: "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%209/1.png",
  },
  {
    name: "Smart Watch",
    description: "Fitness smartwatch for tracking health activities.",
    price: 149,
    stock: 25,
    category: "Wearables",
    imageUrl: "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/1.png",
  },
  {
    name: "Digital Camera",
    description: "High quality camera for photos and videos.",
    price: 699,
    stock: 12,
    category: "Cameras",
    imageUrl: "https://cdn.dummyjson.com/products/images/cameras/Apple%20iPhone/1.png",
  },
  {
    name: "Gaming Mouse",
    description: "Ergonomic mouse with adjustable DPI.",
    price: 49,
    stock: 50,
    category: "Gaming",
    imageUrl: "https://cdn.dummyjson.com/products/images/laptops/HP%20Victus%2016/1.png",
  },
  {
    name: "Power Bank",
    description: "Portable fast charging battery pack.",
    price: 39,
    stock: 70,
    category: "Accessories",
    imageUrl: "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods/1.png",
  },
  {
    name: "Bluetooth Speaker",
    description: "Portable speaker with deep bass sound.",
    price: 79,
    stock: 45,
    category: "Audio",
    imageUrl: "https://cdn.dummyjson.com/products/images/mobile-accessories/Redmi%20Bud%20Pro%20Black/1.png",
  },
  {
    name: "Running Shoes",
    description: "Comfortable sports shoes for training and running.",
    price: 89,
    stock: 60,
    category: "Fashion",
    imageUrl: "https://cdn.dummyjson.com/products/images/mens-shoes/Red%20Shoes/1.png",
  },
  {
    name: "Leather Backpack",
    description: "Durable backpack for work and travel.",
    price: 120,
    stock: 30,
    category: "Bags",
    imageUrl: "https://cdn.dummyjson.com/products/images/mens-shirts/Pure%20Cotton%20T-Shirt/1.png",
  },
  {
    name: "Office Chair",
    description: "Comfortable ergonomic chair for office use.",
    price: 250,
    stock: 18,
    category: "Furniture",
    imageUrl: "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/1.png",
  },
  {
    name: "LED Desk Lamp",
    description: "Adjustable LED lamp for home and office.",
    price: 45,
    stock: 55,
    category: "Home",
    imageUrl: "https://cdn.dummyjson.com/products/images/home-decoration/Decoration%20Pendant%20Light/1.png",
  },
  {
    name: "Luxury Watch",
    description: "Classic premium watch with elegant design.",
    price: 299,
    stock: 22,
    category: "Watches",
    imageUrl: "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/1.png",
  },
];